import type { NextRequest } from 'next/server';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { requireAuth,authFailure } from '@/lib/auth';
import { db } from '@/lib/db';
import { fail,ok,serverError } from '@/lib/http';
const schema=z.object({barcode:z.string().min(3).max(100),locationId:z.string().uuid(),condition:z.enum(['GOOD','MINOR_ISSUE','DAMAGED','MISSING_PARTS','NEEDS_MAINTENANCE']).default('GOOD'),notes:z.string().max(2000).optional(),reportIssue:z.boolean().default(false),issueType:z.string().max(120).optional(),clientTransactionId:z.string().uuid().optional()});
export async function GET(request:NextRequest){try{await requireAuth(request,['ADMIN']);const rows=await db()`select s.*,i.barcode,i.name,i.inventory_type,pl.name as previous_location_name,nl.name as new_location_name,u.full_name as scanner_name from ims_scans s join ims_inventory_items i on i.id=s.inventory_item_id left join ims_locations pl on pl.id=s.previous_location_id left join ims_locations nl on nl.id=s.new_location_id left join ims_users u on u.id=s.scanner_user_id order by s.scanned_at desc limit 500`;return ok(rows)}catch(error){const auth=authFailure(error);return auth?fail(auth.message,auth.status):serverError(error)}}
export async function POST(request:NextRequest){try{const actor=await requireAuth(request);const p=schema.safeParse(await request.json());if(!p.success)return fail('Invalid scan',400,p.error.flatten());const d=p.data;const txid=d.clientTransactionId??randomUUID();const sql=db();const result=await sql.begin(async tx=>{const existing=(await tx`select id from ims_scans where client_transaction_id=${txid} limit 1`)[0];if(existing)return {duplicate:true,scanId:existing.id};const item=(await tx`select * from ims_inventory_items where barcode=${d.barcode} and archived=false limit 1 for update`)[0];if(!item)throw new Error('ITEM_NOT_FOUND');const location=(await tx`select id,name from ims_locations where id=${d.locationId} and active=true limit 1`)[0];if(!location)throw new Error('LOCATION_NOT_FOUND');const scans=await tx`insert into ims_scans(inventory_item_id,barcode,previous_location_id,new_location_id,scanner_user_id,condition,notes,client_transaction_id) values(${item.id},${item.barcode},${item.current_location_id},${location.id},${actor.id},${d.condition},${d.notes??null},${txid}) returning *`;await tx`update ims_inventory_items set current_location_id=${location.id},condition=${d.condition},last_scanned_at=now(),last_scanned_by=${actor.id},updated_at=now() where id=${item.id}`;if(d.reportIssue){await tx`insert into ims_issues(inventory_item_id,scan_id,reported_by,issue_type,description) values(${item.id},${scans[0].id},${actor.id},${d.issueType??'GENERAL'},${d.notes??'Issue reported during scan'})`;}return {duplicate:false,scan:scans[0],item:{id:item.id,barcode:item.barcode,name:item.name},previousLocationId:item.current_location_id,newLocation:{id:location.id,name:location.name}}});return ok(result,result.duplicate?200:201)}catch(error){const auth=authFailure(error);if(auth)return fail(auth.message,auth.status);if(error instanceof Error&&error.message==='ITEM_NOT_FOUND')return fail('Item not found',404);if(error instanceof Error&&error.message==='LOCATION_NOT_FOUND')return fail('Location not found or inactive',404);return serverError(error)}}
