'use client';

import { useEffect, useState } from 'react';

type SiteData={assignedLocation:{id:string;name:string;code:string}|null;materials:Array<{id:string;barcode:string;name:string;inventory_type:string;condition:string;status:string;serial_number?:string;last_scanned_at?:string;image_url?:string}>;incomingTransfers:Array<{id:string;barcode:string;name:string;inventory_type:string;condition:string;from_location_name?:string;destination_location_name:string;requested_by_name:string;requested_at:string}>};

export default function SitePage(){
  const[data,setData]=useState<SiteData|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState('');
  async function load(){
    const token=localStorage.getItem('br_token');if(!token){window.location.href='/';return}
    try{const res=await fetch('/api/scanner-site',{cache:'no-store',headers:{Authorization:`Bearer ${token}`}});const body=await res.json();if(!body.success)throw new Error(body.error?.message||'Unable to load site');setData(body.data);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load site')}
  }
  useEffect(()=>{void load()},[]);
  async function decide(id:string,action:'APPROVE'|'REJECT'){
    const token=localStorage.getItem('br_token');if(!token)return;setBusy(id);setError('');
    try{const res=await fetch(`/api/location-transfers/${id}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action})});const body=await res.json();if(!body.success)throw new Error(body.error?.message||'Unable to update transfer');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to update transfer')}finally{setBusy('')}
  }
  const shell:React.CSSProperties={minHeight:'100vh',background:'#f3f1eb',padding:'24px 18px 100px',fontFamily:'system-ui,sans-serif',color:'#252725'};
  const card:React.CSSProperties={background:'#fff',border:'1px solid #dedbd1',borderRadius:18,padding:18,boxShadow:'0 8px 24px rgba(0,0,0,.05)'};
  if(!data)return <main style={shell}><h1>My Site</h1><p>{error||'Loading site inventory…'}</p></main>;
  return <main style={shell}><div style={{maxWidth:980,margin:'0 auto'}}><header style={{marginBottom:22}}><small style={{fontWeight:800,letterSpacing:1}}>BLUE ROCK IMS</small><h1 style={{fontSize:34,margin:'6px 0'}}>{data.assignedLocation?.name||'No site assigned'}</h1><p style={{margin:0,color:'#666'}}>{data.assignedLocation?`Location ${data.assignedLocation.code} · ${data.materials.length} item${data.materials.length===1?'':'s'} on site`:'Ask an administrator to assign this scanner to a location.'}</p></header>{error&&<div style={{...card,marginBottom:16,borderColor:'#d56b5c',color:'#8b3328'}}>{error}</div>}{data.assignedLocation&&<><section style={{marginBottom:24}}><h2>Incoming transfers</h2>{data.incomingTransfers.length===0?<div style={card}>No incoming transfers waiting for approval.</div>:<div style={{display:'grid',gap:12}}>{data.incomingTransfers.map(row=><article key={row.id} style={card}><div style={{display:'flex',gap:12,justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap'}}><div><strong style={{fontSize:18}}>{row.name}</strong><div style={{fontFamily:'monospace',marginTop:4}}>{row.barcode}</div><p style={{margin:'8px 0 0',color:'#666'}}>From {row.from_location_name||'Unassigned'} · Requested by {row.requested_by_name}</p></div><div style={{display:'flex',gap:8}}><button disabled={busy===row.id} onClick={()=>void decide(row.id,'REJECT')} style={{padding:'10px 14px',borderRadius:10,border:'1px solid #c9c5bc',background:'#fff',fontWeight:800}}>Reject</button><button disabled={busy===row.id} onClick={()=>void decide(row.id,'APPROVE')} style={{padding:'10px 14px',borderRadius:10,border:0,background:'#ff8a46',fontWeight:900}}>Approve</button></div></div></article>)}</div>}</section><section><h2>Materials on site</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12}}>{data.materials.map(item=><article key={item.id} style={card}><strong>{item.name}</strong><div style={{fontFamily:'monospace',margin:'5px 0 10px'}}>{item.barcode}</div><div style={{fontSize:14,color:'#666'}}>{item.inventory_type} · {item.condition} · {item.status}</div>{item.last_scanned_at&&<small style={{display:'block',marginTop:8,color:'#888'}}>Last scanned {new Date(item.last_scanned_at).toLocaleString()}</small>}</article>)}</div>{data.materials.length===0&&<div style={card}>No materials are currently assigned to this site.</div>}</section></>}</div></main>;
}
