import type { NextRequest } from 'next/server';
import { hash } from 'bcryptjs';
import { z } from 'zod';
import { requireAuth,authFailure } from '@/lib/auth';
import { db } from '@/lib/db';
import { fail,ok,serverError } from '@/lib/http';
const schema=z.object({fullName:z.string().min(2).max(120).optional(),role:z.enum(['ADMIN','SCANNER']).optional(),active:z.boolean().optional(),password:z.string().min(12).max(200).optional()});
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{const actor=await requireAuth(request,['ADMIN']);const {id}=await params;const p=schema.safeParse(await request.json());if(!p.success)return fail('Invalid user update',400,p.error.flatten());const sql=db();const current=(await sql`select * from ims_users where id=${id} limit 1`)[0];if(!current)return fail('User not found',404);if(actor.id===id&&p.data.active===false)return fail('You cannot disable your own account',409);const passwordHash=p.data.password?await hash(p.data.password,12):current.password_hash;const rows=await sql`update ims_users set full_name=${p.data.fullName??current.full_name},role=${p.data.role??current.role},active=${p.data.active??current.active},password_hash=${passwordHash},updated_at=now() where id=${id} returning id,username,full_name,role,active,last_login_at,updated_at`;return ok(rows[0])}catch(error){const auth=authFailure(error);return auth?fail(auth.message,auth.status):serverError(error)}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{const actor=await requireAuth(request,['ADMIN']);const {id}=await params;if(actor.id===id)return fail('You cannot disable your own account',409);const rows=await db()`update ims_users set active=false,updated_at=now() where id=${id} returning id,username,full_name,role,active`;return rows[0]?ok(rows[0]):fail('User not found',404)}catch(error){const auth=authFailure(error);return auth?fail(auth.message,auth.status):serverError(error)}}
